export const TRANSITION_WORDS = [
  "however",
  "therefore",
  "moreover",
  "furthermore",
  "consequently",
  "additionally",
  "in contrast",
  "similarly",
  "as a result",
  "for example",
  "for instance",
  "on the other hand",
  "nevertheless",
  "meanwhile",
  "likewise",
  "in addition",
  "specifically",
  "in particular",
  "notably",
  "importantly",
];
