import type { AnalyzerResultType } from "../../analyzer/schema.js";

export function renderMarkdown(result: AnalyzerResultType): string {
  const lines: string[] = [];

  lines.push(`# GEO Audit Report`);
  lines.push("");
  lines.push(`**URL:** ${result.url}`);
  lines.push(
    `**Overall Score:** ${result.overallScore}/100 (Grade: ${result.grade})`,
  );
  lines.push(`**Points:** ${result.totalPoints}/${result.maxPoints}`);
  lines.push(`**Analyzed:** ${result.analyzedAt}`);
  lines.push("");

  // Categories
  lines.push("## Category Breakdown");
  lines.push("");
  lines.push("| Category | Score | Max | Percentage |");
  lines.push("|----------|-------|-----|------------|");

  for (const category of Object.values(result.categories)) {
    const pct =
      category.maxScore > 0
        ? Math.round((category.score / category.maxScore) * 100)
        : 0;
    lines.push(
      `| ${category.name} | ${category.score} | ${category.maxScore} | ${pct}% |`,
    );
  }

  lines.push("");

  // Detailed factors
  for (const category of Object.values(result.categories)) {
    lines.push(`### ${category.name}`);
    lines.push("");
    lines.push("| Factor | Score | Status | Details |");
    lines.push("|--------|-------|--------|---------|");

    for (const factor of category.factors) {
      const statusIcon =
        factor.status === "good"
          ? "pass"
          : factor.status === "neutral"
            ? "-"
            : factor.status === "needs_improvement"
              ? "warn"
              : "fail";
      lines.push(
        `| ${factor.name} | ${factor.score}/${factor.maxScore} | ${statusIcon} | ${factor.value} |`,
      );
    }

    lines.push("");
  }

  // Recommendations
  if (result.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");

    for (const rec of result.recommendations) {
      const tag =
        rec.priority === "high"
          ? "**HIGH**"
          : rec.priority === "medium"
            ? "*MEDIUM*"
            : "LOW";
      lines.push(
        `- [${tag}] **${rec.factor}** (${rec.category}): ${rec.recommendation}`,
      );
    }

    lines.push("");
  }

  lines.push("---");
  lines.push(
    `*Generated by generative-engine-audit-cli v${result.meta.version}*`,
  );

  return lines.join("\n");
}
