import type { AnalyzerResultType } from "../../analyzer/schema.js";

export function renderMarkdown(result: AnalyzerResultType): string {
  const lines: string[] = [];

  lines.push(`# AI SEO Audit`);
  lines.push("");
  lines.push(`**URL:** ${result.url}`);
  lines.push("");

  lines.push("| Category | Score | Percentage |");
  lines.push("|----------|-------|------------|");

  for (const category of Object.values(result.categories)) {
    const pct =
      category.maxScore > 0
        ? Math.round((category.score / category.maxScore) * 100)
        : 0;
    lines.push(
      `| ${category.name} | ${category.score}/${category.maxScore} | ${pct}% |`,
    );
  }

  lines.push("");

  lines.push(
    `## Overall: ${result.overallScore}/100 (${result.grade}) - ${result.totalPoints}/${result.maxPoints} pts`,
  );
  lines.push("");

  for (const category of Object.values(result.categories)) {
    const pct =
      category.maxScore > 0
        ? Math.round((category.score / category.maxScore) * 100)
        : 0;
    lines.push(`### ${category.name} (${pct}%)`);
    lines.push("");
    lines.push("| Factor | Score | Status | Details |");
    lines.push("|--------|-------|--------|---------|");

    for (const factor of category.factors) {
      const statusIcon =
        factor.status === "good"
          ? "pass"
          : factor.status === "neutral"
            ? "-"
            : factor.status === "needs_improvement"
              ? "warn"
              : "fail";
      lines.push(
        `| ${factor.name} | ${factor.score}/${factor.maxScore} | ${statusIcon} | ${factor.value} |`,
      );
    }

    lines.push("");
  }

  if (result.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");

    const categoryNames = Object.values(result.categories).map((c) => c.name);

    for (const categoryName of categoryNames) {
      const categoryRecs = result.recommendations.filter(
        (r) => r.category === categoryName,
      );
      if (categoryRecs.length === 0) continue;

      lines.push(`### ${categoryName}`);
      lines.push("");

      for (const rec of categoryRecs) {
        const tag =
          rec.priority === "high"
            ? "**HIGH**"
            : rec.priority === "medium"
              ? "*MED*"
              : "LOW";
        lines.push(`- [${tag}] **${rec.factor}**: ${rec.recommendation}`);
      }

      lines.push("");
    }
  }

  lines.push("---");
  lines.push(
    `*Generated by aiseo-audit v${result.meta.version} | ${result.analyzedAt} | ${result.meta.analysisDurationMs}ms*`,
  );

  return lines.join("\n");
}
