import type { AnalyzerResultType } from "../../analyzer/schema.js";
import type { RecommendationType } from "../../recommendations/schema.js";
import {
  isSuccessResult,
  type SitemapUrlResultType,
} from "../../sitemap/schema.js";

export const PASS_PCT = 90;
export const AVERAGE_PCT = 50;

export type ScoreBandType = "pass" | "average" | "fail";

export function scoreBand(pct: number): ScoreBandType {
  if (pct >= PASS_PCT) return "pass";
  if (pct >= AVERAGE_PCT) return "average";
  return "fail";
}

export function percent(score: number, maxScore: number): number {
  return maxScore > 0 ? Math.round((score / maxScore) * 100) : 0;
}

export function priorityLabel(
  priority: RecommendationType["priority"],
): "HIGH" | "MED" | "LOW" {
  if (priority === "high") return "HIGH";
  if (priority === "medium") return "MED";
  return "LOW";
}

export function groupRecommendationsByCategory(
  result: Pick<AnalyzerResultType, "recommendations" | "categories">,
): Array<[string, RecommendationType[]]> {
  const groups: Array<[string, RecommendationType[]]> = [];
  for (const category of Object.values(result.categories)) {
    const recs = result.recommendations.filter(
      (r) => r.category === category.name,
    );
    if (recs.length > 0) groups.push([category.name, recs]);
  }
  return groups;
}

export function hasHttpUrls(urlResults: SitemapUrlResultType[]): boolean {
  return urlResults
    .filter(isSuccessResult)
    .some((r) => r.result.url.startsWith("http://"));
}

export const HTTP_AUDIT_NOTE =
  "Audited over HTTP. Domain signals (robots.txt, llms.txt) may differ in production.";

export const SITEMAP_HTTP_AUDIT_NOTE =
  "Some URLs were audited over HTTP. Domain signals (robots.txt, llms.txt) may differ in production.";

export function generatedByLine(version: string): string {
  return `Generated by aiseo-audit v${version}`;
}

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function escapeMarkdownTableCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

export function markdownFenceFor(content: string): string {
  const longestRun = content
    .split(/[^`]+/)
    .reduce((max, run) => Math.max(max, run.length), 0);
  return "`".repeat(Math.max(3, longestRun + 1));
}
