import type { AnalyzerResultType } from "../../analyzer/schema.js";
import type { RecommendationType } from "../../recommendations/schema.js";
import type { GateResultType, StageScoresType } from "../../scoring/schema.js";
import {
  isSuccessResult,
  type SitemapUrlResultType,
} from "../../sitemap/schema.js";

export const PASS_PCT = 90;
export const AVERAGE_PCT = 50;

export type ScoreBandType = "pass" | "average" | "fail";

export function scoreBand(pct: number): ScoreBandType {
  if (pct >= PASS_PCT) return "pass";
  if (pct >= AVERAGE_PCT) return "average";
  return "fail";
}

export function percent(score: number, maxScore: number): number {
  return maxScore > 0 ? Math.round((score / maxScore) * 100) : 0;
}

export function priorityLabel(
  priority: RecommendationType["priority"],
): "HIGH" | "MED" | "LOW" {
  if (priority === "high") return "HIGH";
  if (priority === "medium") return "MED";
  return "LOW";
}

export function groupRecommendationsByCategory(
  result: Pick<AnalyzerResultType, "recommendations" | "categories">,
): Array<[string, RecommendationType[]]> {
  const groups: Array<[string, RecommendationType[]]> = [];
  for (const category of Object.values(result.categories)) {
    const recs = result.recommendations.filter(
      (r) => r.category === category.name,
    );
    if (recs.length > 0) groups.push([category.name, recs]);
  }
  return groups;
}

export function hasHttpUrls(urlResults: SitemapUrlResultType[]): boolean {
  return urlResults
    .filter(isSuccessResult)
    .some((r) => r.result.url.startsWith("http://"));
}

export const HTTP_AUDIT_NOTE =
  "Audited over HTTP. Domain signals (robots.txt, llms.txt) may differ in production.";

export const SITEMAP_HTTP_AUDIT_NOTE =
  "Some URLs were audited over HTTP. Domain signals (robots.txt, llms.txt) may differ in production.";

export function generatedByLine(version: string): string {
  return `Generated by aiseo-audit v${version}`;
}

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function escapeMarkdownTableCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

export function markdownFenceFor(content: string): string {
  const longestRun = content
    .split(/[^`]+/)
    .reduce((max, run) => Math.max(max, run.length), 0);
  return "`".repeat(Math.max(3, longestRun + 1));
}

export const VISIBLE_RECOMMENDATION_COUNT = 3;

export const NON_ADDITIVE_RECS_NOTE =
  "Apply the top items and re-measure before continuing - gains do not stack additively, and each addition competes for the same content budget.";

export const PRODUCT_PAGE_WARNING =
  "Generic content optimization measurably hurt product pages in end-to-end tests; prioritize price, specs, and comparisons over rewriting.";

export const SUPPRESSED_STAGE_LABEL = "suppressed (eligibility failed)";

export const UNSCORED_DIAGNOSTIC_LABEL = "unscored diagnostic";

export const STAGE_LABELS: Record<keyof StageScoresType, string> = {
  technicalEligibility: "Technical Eligibility",
  retrievalAlignment: "Retrieval Alignment",
  citationFitness: "Citation Fitness",
  provenance: "Provenance",
};

export function enginePresetBanner(
  engine: AnalyzerResultType["meta"]["engine"],
): string | null {
  if (!engine || engine === "generic") return null;
  return `Experimental engine preset: ${engine}`;
}

export function isProductPage(result: AnalyzerResultType): boolean {
  return (
    result.meta.domain === "product" ||
    result.rawData.domainDetected === "product"
  );
}

export function trippedGateLine(gate: GateResultType): string {
  return `capped at ${gate.capPct}: ${gate.label}`;
}

export function trippedGates(stages: StageScoresType): GateResultType[] {
  return stages.citationFitness.gates.filter(
    (gate) => gate.status === "tripped",
  );
}

export function stagePctLabel(pct: number | null, suppressed: boolean): string {
  if (suppressed) return SUPPRESSED_STAGE_LABEL;
  return pct === null ? "n/a" : `${pct}%`;
}

export function orderFactorsForDisplay<T extends { status: string }>(
  factors: T[],
): T[] {
  const scored = factors.filter((factor) => factor.status !== "info");
  const diagnostics = factors.filter((factor) => factor.status === "info");
  return [...scored, ...diagnostics];
}

export function visibleRecommendations(
  recommendations: RecommendationType[],
): RecommendationType[] {
  return recommendations.slice(0, VISIBLE_RECOMMENDATION_COUNT);
}

export function hiddenRecommendationsNote(
  recommendations: RecommendationType[],
): string | null {
  const hidden = recommendations.length - VISIBLE_RECOMMENDATION_COUNT;
  return hidden > 0 ? `${hidden} more in JSON output` : null;
}
